@startuml event tracker
entity "User" as User {
  + ID : int
  --
  FirstName : nvarchar(70)
  LastName : nvarchar(70)
  Email : nvarchar(140)
  Pass : nvarchar(16)
  AvatarUrl : nvarchar(40)
  Bio : nvarchar(MAX)
  Role : enum(RoleType)  // Admin, Organizador, Invitado
}

entity "Event" as Event {
  + ID : int
  --
  Name : nvarchar(70)
  Description : nvarchar(MAX)
  StartDateTime : datetime
  EndDateTime : datetime
  Capacity : int
  CreatorID : int
  Status : enum(EventStatus)  // Borrador, Publicado, Concluido, Cancelado
  FlyerUrl : nvarchar(100)
  Location : nvarchar(200)
}

entity "EventInvitation" as EventInvitation {
  + ID : int
  --
  EventID : int
  UserID : int
  CreatorID : int  // ID del usuario que crea la invitación
  ResponseStatus : varchar(20)  // Aceptada, Rechazada, Tal vez
  SentDate : datetime
  ResponseDate : datetime
}

entity "EventPost" as EventPost {
  + ID : int
  --
  EventID : int
  UserID : int
  Text : nvarchar(MAX)
  CreationDate : datetime
}

User ||--o{ Event : "creates"
User ||--o{ EventInvitation : "receives"
User ||--o{ EventInvitation : "creates"
Event ||--o{ EventInvitation : "has"
Event ||--o{ EventPost : "has"
User ||--o{ EventPost : "posts"
@enduml
